### ISSUE TITLE
Import URL from Documents to Problems/Diagnoses

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile-React-Core#114]
When we import Data using Documents heading (Diagnosis List) for example:
http://prntscr.com/i86vlq
http://prntscr.com/i87oci 

When we send POST to create Diagnoses we send these fields to mark these heading that they were created from Documents and have this imported URL : 
http://joxi.net/nAyLDXLfYzeoz2
But we get them empty in response:
http://joxi.net/Drl7DO7svgjL3A 

Could you check it please?

Related issue: https://github.com/RippleOSI/Ripple-Qewd/issues/79

**Comment by anna-otrokhova** [comment]
@tony-shannon 
 We would need an assistance from Rob as backend side doesn't send the expected data.
Could you ask Rob to check, please, as I can't mention him here?

**Comment by robtweed** [comment]
Sorry, I don't understand the issue sufficiently.  What API / URL are we talking about?  eg is it

  POST /api/documents/patient/:patientId/:host ?

or are you referring to a different API?

**Comment by anna-otrokhova** [comment]
@robtweed 
When we import documents in Documents heading we use the following requests:

Documents
Propblem/Diagnosis
GET /api/patients/{patientId}/problems/{sourceId}
PUT /api/patients/{patientId}/problems/{sourceId}
POST /api/patients/{patientId}/problems

Allergies
GET /api/patients/{patientId}/allergies/{sourceId}
PUT /api/patients/{patientId}/allergies/{sourceId}
POST /api/patients/{patientId}/allergies

Medications
GET /api/patients/{patientId}/medications/{sourceId}
PUT /api/patients/{patientId}/medications/{sourceId}
POST /api/patients/{patientId}/medications

We need these fields to be added:
isImport: boolean,
originalSource: string
originalComposition: string

These three fields should be saved on the server with  POST and PUT и be returned with GET

**Comment by robtweed** [comment]
I don't remember enough about how Documents are supposed to work and the mechanics that are supposed to take place.  It would be useful to have a short screen cast showing the steps typically involved in importing documents, or a document that steps me through what you do so that I can reproduce the issue and trace through the middle tier code.

**Comment by robtweed** [comment]
One thing I don't understand is: where do the Discharge Summary records for 9999999000 and 9999999068 come from?  I don't see a Create or Add button anywhere that allows one to be added via PulseTile.   I'm sure I once knew about this, but I really can't remember how these Documents are supposed to work

**Comment by anna-otrokhova** [comment]
@robtweed 
I try to record a video. The templates of Documents are taken from DB. We don't create them. For now, there is only one template we get -> Discharged Summary ( but there could be also Referrals Summary, they are a little bit different). By the way, there is an issue  on github to add it -> https://github.com/PulseTile/PulseTile-React/issues/132

**Comment by anna-otrokhova** [comment]
Here is a record https://drive.google.com/file/d/1T1Iyj8SxiXkCi4ztrwTDlytICqlCWp2e/view

**Comment by kuvakina** [comment]
In current Angular and React versions I don't see URLs, so could we consider this task Done:

https://www.screencast.com/t/42EHOz7mQ

https://www.screencast.com/t/eDFLjNKZ
