### ISSUE TITLE
Logout API needs to be added to PHR UI

### ISSUE THREAD

**Issue by robtweed** [PulseTile/PulseTile-React-Core#118]
The Gov UK Verify (OpenID Connect) -based login mechanism requires an explicit logout to be sent to their server in order to terminate a user's session.  I can do this from the middle tier, but in order to do this, I'll need to receive a signal from the UI that the user has clicked the logout button.

Could you therefore add this - ie when the User's Logout button is clicked send:

  GET /api/logout

to the middle tier.  The UI should then await the OK response from the middle tier for this API before reloading index.html and sending its /api/initialise request (which starts the login redirection sequence again)

Rob

**Comment by robtweed** [comment]
Just to clarify, the UI should also delete the JSESSIONID cookie when the logout button is clicked

**Comment by anna-otrokhova** [comment]
It was done from our side. Rob confirmed that it works

**Comment by anna-otrokhova** [comment]
@robtweed 
Could you please add this functionality to the main React version too? 
We have configured for both LeedsPHR and React boxes.

**Comment by kbeloborodko** [comment]
@robtweed could you please advise when will you be able to add logout functionality to the dev.ripple test environment?

**Comment by robtweed** [comment]
It's done - now available on both dev and showcase
