### ISSUE TITLE
Transfer of care issue 

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile-React-Core#122]
We noticed that sometimes when we try to edit Transfer of Care and clicking on some of the records in the table:
For example Transfer of Care #11 -> click on "Latest Vitals Data (New score:9)"
http://prntscr.com/iepvkl
http://joxi.net/BA0nJ4nsJnXYwm
We get an error 400 from back end
Though the same GET request for the same record (with the same sourdeid) works on Vitals tab -> http://joxi.net/v29dzJds3owJXm

Could you check why we get an error, please?
Related issue: https://github.com/RippleOSI/Ripple-Qewd/issues/83

**Comment by anna-otrokhova** [comment]
@tony-shannon 
Could you ask Rob to have a look at, please?

All works by front end side have been done. This task might be tested after Rob's investigation.

**Comment by robtweed** [comment]
OK there were 2 issues - 

1) The middle tier will now fetch and cache a heading if a detail record is requested.  Previously it was assumed that a detail record for a heading would only be requested after the summary records were requested (which results in the heading being cached).  However in the case of TOCs, we can end up requesting a medications detail record before medications have been cached.  It will now handle this correctly (at least on dev for now).

2) The medications record with sourceId 9302be50-97a2-4771-aa0a-d825787ec445 does not actually exist.  My guess is that it once did exist but was manually deleted.  Unfortunately this potentially leaves dead references in the TOC file.  It would be way too inefficient to go looking for these when a heading detail record is deleted, so instead the middle tier will do a consistency check on a TOC record when it is retrieved, and remove any orphaned heading records from it, refile it and send the cleaned-up data to PulseTile.  As a result, you may find TOC records with no attached headings.

I've updated dev but not showcase with this new logic - could you test it out and confirm it's not corrupting good data, but cleaning up TOC records correctly when a heading sourceId has been deleted

**Comment by kbeloborodko** [comment]
@robtweed we tested the new logic on the dev environment and it works as intended, at least for now, we did not find any issues. Thank you.
CC: @tony-shannon

**Comment by tony-shannon** [comment]
lets close for now, thanks
