### ISSUE TITLE
End 2 End tests issue to check 

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile-React-Core#130]
Recently some tests that were successful before started to fail now mostly on React. Bu we are going to check them and add more information.

**Comment by anna-otrokhova** [comment]
@tony-shannon 
The Headings tests failed because we slightly altered the application load and the selection of the elements in the tests worked before the element appeared on the page. 
The End2End tests were corrected. This issue has been solved.

**Comment by tony-shannon** [comment]
reopen on discussion with @kuvakina 
maybe link to issue 194?

**Comment by kuvakina** [comment]
@tony-shannon 

Right now E2E tests are working correctly. Could we move this issue to Done?

**Comment by PhilBarrett** [comment]
Closing with #194 remaining open to cover this off
