### ISSUE TITLE
Patient Counts being invoked for too many patients at a time

### ISSUE THREAD

**Issue by robtweed** [PulseTile/PulseTile-React-Core#139]
I've just noticed what I believe is an error - at the very least an inefficiency - in the patient counts API as used by the Leeds PHR UI (and probably in Ripple too).  This is the API I'm referring to:

GET /api/patients/{patientId}/counts

The original idea was that this API should be invoked for ONLY those patients currently displayed in the Patient Listings screen - ie the current (up to) 10 on display at any one time, so we can as quickly as possible, with the minimum of overhead, fetch and display the numbers of orders and results for each patient displayed for the selected setting (eg Neighbourhood).

What is actually happening is that requests are being sent for ALL patients in that setting.  So, if you select Neighbourhood, around 30 requests are sent out, instead of just the 10 currently on display.  This hammers the back end, largely unnecessarily, and slows down the screen.

Can I suggest this is fixed?  It will help improve the responsiveness of these screens

**Comment by BogdanScherban** [comment]
@robtweed 

Rob, do I understand correctly, that I need to send requests only for current 10 patients depending on pagination position? Instead of requests for all patients?

**Comment by robtweed** [comment]
Yes that is what it should do - only retrieve the counts for the patients currently on display.  So each time you select a next page it should fetch the counts for the new page of patients.   

Currently, if there are 200 patients in a group, then it's sending out 200 count requests, which is very wasteful and hammers the back-end needlessly.

**Comment by juliashulga** [comment]
Hi @robtweed 

1) Is there a way to receive from backend the total number of users corresponding to the search parameter?
2) And also, is there a way to receive these users with some limit?
(For instance, if I pass the parameter offset0 -> backend send the first 20 users, from 0 to 19)?

Could you please advise?

**Comment by juliashulga** [comment]
@tony-shannon 
Oleg reduced the number of counts so that they are only dedicated to the certain page only.

When I do testing I see that it gets all the patients but not by page - https://prnt.sc/jzv62s
Do we need to get only that number of patients which is corresponding to the search parameter ? so it sends only 10 requests per one page and all the rest by going through next pages ?

**Comment by kuvakina** [comment]
@tony-shannon Sorry, we might have to check this issue one more time: last time I checked it, it was working but now it again loads all counts. I'll try to update you today till evening regarding this problem.

**Comment by tony-shannon** [comment]
OK thanks @kuvakina

**Comment by tony-shannon** [comment]
thank you

**Comment by tony-shannon** [comment]
@kuvakina  will update this issue with more feedback

NB This issue can be parked for now, as focus on PHR aspects currently

**Comment by kuvakina** [comment]
@tony-shannon 

UPD:

I've just checked this issue on the site: it's working correctly. 

I'll move it to Testing and will monitor it.

**Comment by kuvakina** [comment]
@tony-shannon 

It's still working correctly. Could we move this issue to Done?

**Comment by PhilBarrett** [comment]
Working fine.
