### ISSUE TITLE
Change required to Leeds PHR Sign Out

### ISSUE THREAD

**Issue by robtweed** [PulseTile/PulseTile-React-Core#140]
Having moved the UI to use our own OpenID Connect Server for authentication, I've discovered that the mechanism I previously figured out for user sign out was working incorrectly (though it did work against the Gov.UK Verify sandbox).

What I now need you to do is as follows:

- when the PulseTile User Sign Out button is pressed, it should send the GET /api/logout request as before

- the response returned will now provide you with a JSON body containing a redirection URL, eg:

         {
               redirectURL: 'http://www.mgateway.com:8089/session/end'
          }

PulseTile should:

1) delete the JSESSIONID cookie

2)  make a redirection to the redirection URL, eg

         window.location=response.redirectURL;

That's all that PulseTile now needs to do.

The OpenID Connect server will do the rest, removing the logged in user from its session information and deleting its own cookies, and will ultimately redirect the browser back to the PulseTile home page.  From there, PulseTile will take over, re-directing back to the OpenID Server which will bring up the username/password form.

I've made a hardwired change to the UI at dev.ripple.foundation:8000 which demonstrates how it will now work

**Comment by juliashulga** [comment]
Tested on 9999999000 and 99999990015 users - sign in / sign out at dev.ripple.foundation:8000 works properly.

@tony-shannon can we consider the task is done ?

**Comment by tony-shannon** [comment]
thanks Julia
I suggest you leave your Helm PHR browser tab open for a while and then see if logouts work fine.
The Helm PHR demo needs a lot of testing to iron out bugs so I would rather this is retested several times before closing please
thanks
Tony

**Comment by kuvakina** [comment]
Update on 04.07.2018

Sign in / sign out for 9999999000 and 99999990015 users at dev.ripple.foundation:8000 works properly for the following browsers:
Desktop:
- Chrome - YES
- Mozilla - YES
- Safari - YES
- IE11 - there is an issue, it's being fixed right now
Mobile:
- Safari iOS11 - YES
- Chrome - YES

@tony-shannon after we fix issues with IE11, can we consider this task as Done?

**Comment by kuvakina** [comment]
UPD:

IE11: We can log in now, log out but sometimes loading takes too much time (around 7-20 sec). And sometimes you have to reload the page or clear cookies to log in / log out.

We'll look how to fix it.

**Comment by tony-shannon** [comment]
thank you @kuvakina

**Comment by kuvakina** [comment]
@tony-shannon 

Considering the error #176 , should we leave this issue open for now?

**Comment by polesskiy-dev** [comment]
I see myself in Assignees list, how I can help you with this problem? Cause I think I loose context of the project long time ago.

**Comment by kuvakina** [comment]
Created the issue for this bug - #236

And asked Oleg to look into it.

**Comment by PhilBarrett** [comment]
with #236 remaining open, @kuvakina I think this issue can be closed

**Comment by kuvakina** [comment]
@PhilBarrett yes, I think we can close this issue, as we don't have problems with logout.
