### ISSUE TITLE
Split modules into core + plugins

### ISSUE THREAD

**Issue by kbeloborodko** [PulseTile/PulseTile-React-Core#143]

**Comment by tony-shannon** [comment]
eg : Top 3 Things, PROMs and Feeds to a separate repository under https://github.com/pulsetile-plugins account

**Comment by tony-shannon** [comment]
need to follow the pattern in the Angular repo

Core repo has small number of modules

Silver plugins has many more modules ( stable ones)

Bronze plugins are new/under dev etc
