### ISSUE TITLE
Plugins tidyup

### ISSUE THREAD

**Issue by juliashulga** [PulseTile/PulseTile-React-Core#151]

**Comment by tony-shannon** [comment]
Need to mimic PulseTile (Angular) Core + Plugins
See those repos

See this one about moving PROMS, Top 3 things etc to the Plugins Repo
#143

**Comment by BogdanScherban** [comment]
@tony-shannon @kbeloborodko 
I've extracted all non-core plugins from the Main repository and relocated them to separate plugin's repositories.

Pull-requests for plugins repositories (Carbon, Bronze and Silver) were approved by @kbeloborodko earlier.

PR for plugins extracting from the Main project is ready and needs in code review by @kbeloborodko

**Comment by kuvakina** [comment]
@tony-shannon 
The plugins were added to LeedsCC (#180)

Can we consider this issue Done?

**Comment by tony-shannon** [comment]
Can do for now, thanks
