### ISSUE TITLE
Expired session should force application logout at UI 

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/PulseTile-React-Core#153]
OK so if PulseTile gets an error response telling it that the token is invalid or expired, it should be handling that by re-loading the app from the top again, perhaps initially telling the user that they've timed ou

**Comment by tony-shannon** [comment]
here I had logged in and then went away , got distracted

when I returned I wanted to check the meds, but the session had timed out

the application should have forced me to login again

It did not
It kept this display

![image](https://user-images.githubusercontent.com/939996/40652429-241b4364-6330-11e8-816f-339a10278e8c.png)

**Comment by tony-shannon** [comment]
and again cant sign in
![image](https://user-images.githubusercontent.com/939996/41170892-46352028-6b46-11e8-8cd2-275aec1f208f.png)

**Comment by kuvakina** [comment]
@tony-shannon Here you can see that force application logout is working for all browsers (exect IE11, we still working on this issue):  

Edge:
![153_edge](https://user-images.githubusercontent.com/40596171/42564443-7001cd52-8509-11e8-8b19-eb37b32d5b2e.png)
Mozilla Firefox:
![153_ff](https://user-images.githubusercontent.com/40596171/42564444-70272f48-8509-11e8-841f-35fe0e3b544e.png)
Chrome:
![153_chrome](https://user-images.githubusercontent.com/40596171/42564446-7064bc0a-8509-11e8-9f13-9d7d110eb195.png)
Chrome (Android):
![153_chrome andr](https://user-images.githubusercontent.com/40596171/42564445-70458d1c-8509-11e8-89bc-6c95bc2ed601.png)
Safari iOS11:
![153_ios11](https://user-images.githubusercontent.com/40596171/42565655-bc6d9934-850c-11e8-8e8c-630cb85fed6f.png)

**Comment by tony-shannon** [comment]
thanks for update @kuvakina

**Comment by kuvakina** [comment]
UPD:

IE11: We are forcefully logout after session expired.  
![out_ie11](https://user-images.githubusercontent.com/40596171/44100571-0ba01e0e-9fee-11e8-9d6d-47c4547244bf.png)

But sometimes loading takes too much time (around 7-20 sec). And sometimes you have to reload the page or clear cookies to log out. And also as you can see, the message says that there is an error - I think it could be related to loading problem.

We'll look how to fix it.

**Comment by tony-shannon** [comment]
thanks again

**Comment by kuvakina** [comment]
@tony-shannon 

We have the error in IE11 (issue #176). But expired session forces the application to log out at UI in all browsers. Could we move this issue to Done?
