### ISSUE TITLE
Patient Summary screen - Loading of table behaviour

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/PulseTile-React-Core#165]
With a patient with a large data set, when loading it briefly shows large empty table, before being loaded properly. See video, example with Problems/diagnosis in this case.

![problems diagnosis homescreen](https://user-images.githubusercontent.com/12699244/40990558-207c374a-68e9-11e8-8a43-524d1742c5a5.gif)

**Comment by BogdanScherban** [comment]
Fixed. The issue was in the same names of heading in synopsis and total list in Store.

I added a condition which output only four first rows.

**Comment by tony-shannon** [comment]
that PR fixes  #165
