### ISSUE TITLE
Cross browsers testing

### ISSUE THREAD

**Issue by juliashulga** [PulseTile/PulseTile-React-Core#170]
- [ ] #177  in FireFox sign-out isn't working at all
- [ ] #176 HELM PHR doesn't load in IE 11

**Comment by tony-shannon** [comment]
@simongamester thanks for a view on target for this

**Comment by simongamester** [comment]
@tony-shannon Recommended browsers continually changes, however I would suggest the following based on current web usage stats - https://www.w3schools.com/BROWSERS/default.asp

Desktop
- Chrome v66 (latest) to v63
- IE11 (sorry)
- Edge (latest)
- Firefox (latest)
- Safari (latest)

Mobile
- Safari iOS11 (latest)
- Chrome (latest)

BrowserStack allow for live testing on all popular browsers above and currently offer free unlimited access for open source projects, so would be worth setting up an account - https://www.browserstack.com/open-source . We'll need to complete an application form to qualify.

**Comment by PhilBarrett** [comment]
BrowserStack OS application approved. Adding browserstack logo and acknowledgement into Repo before adding team account access

**Comment by PhilBarrett** [comment]
Browserstack account now set up and access shared. @kbeloborodko please also let me know if you'd also like access.

**Comment by kbeloborodko** [comment]
Hi, @PhilBarrett, yes, I would also like to have access if possible. Thank you!

**Comment by kuvakina** [comment]
@tony-shannon For now I can't suggest it, we still have issues with IE11. 

Oleg has a few ideas about why we can't log in to IE11, but I think he'll need Rob's help (the issue might be related to the backend and Oleg wants to check it).

**Comment by tony-shannon** [comment]
thansk for update @kuvakina 
Lets leave this open for now then
thanks

**Comment by kuvakina** [comment]
UPD:

IE11: We can log in now, log out and also force logout after session expired, but sometimes loading takes too much time (around 7-20 sec). And sometimes you have to reload the page or clear cookies to log in / log out.

We'll look how to fix it.

**Comment by tony-shannon** [comment]
thanks @kuvakina

**Comment by kuvakina** [comment]
@tony-shannon 

Despite the error that described in #176 , we can login and forcefully logout from the app. So can we consider this task Done?

**Comment by PhilBarrett** [comment]
With #176 remaining open with different issues, this can be considered complete
