### ISSUE TITLE
Plugins to add to LeedsCC

### ISSUE THREAD

**Issue by juliashulga** [PulseTile/PulseTile-React-Core#180]
The following plugins should be in LeedsCC

- Diagnosis, 
- contacts, 
- allergies, 
- medications, 
- Vaccinations, 
- Feeds
-  top 3 things

**Comment by tony-shannon** [comment]
@kuvakina has this been done?

**Comment by kuvakina** [comment]
@tony-shannon yes, this one is done and we merged it. Can we put it to Done?

**Comment by tony-shannon** [comment]
ok @kuvakina please do
