### ISSUE TITLE
Data isn't being brought over

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/PulseTile-React-Core#187]
It seems server doesn't return Vaccination and Contacts information for user hashim.booth@ripple.foundation , as you can see on the console: 
For Vaccination:
![](https://content.screencast.com/users/Sasha1228/folders/Jing/media/28fd6efd-241a-43a8-9141-37294e838583/2018-07-16_1426.png)
For Contacts:
![](https://content.screencast.com/users/Sasha1228/folders/Jing/media/c5ba801d-9f1c-496a-b1a3-194a4182c6fe/2018-07-16_1427.png)

@robtweed Could you please see into this issue?

**Comment by tony-shannon** [comment]
thanks Aleksandra

Think this issue should be on the LeedsPHR repo tbh
T

**Comment by kuvakina** [comment]
@tony-shannon Sorry, re-make it

**Comment by kuvakina** [comment]
Issue solved: have to reboot EtherCIS

**Comment by kuvakina** [comment]
This works correctly.
