### ISSUE TITLE
Issue with conecting to Remote desktop

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/PulseTile-React-Core#189]
We had a problem to connect to the Remote desktop to perform End2End testing, even using instruction. 

The main problem was that our connection was terminated by the remote computer (before I used VNC extension for Chrome):

First I checked on the server (we used PuTTY) if there are any processes and if yes, on which port:
![putty](https://user-images.githubusercontent.com/40596171/42943088-862321f0-8b6a-11e8-9ff6-00096fd1e623.png)

So I tried to connect with port 5901:
![vnc01](https://user-images.githubusercontent.com/40596171/42943141-a567d54c-8b6a-11e8-8b83-018748371c59.png)

And result:
![vnc02](https://user-images.githubusercontent.com/40596171/42943156-ab408928-8b6a-11e8-9af1-e922c32a9602.png)

Then I tried to connect with another port:
![vnc03](https://user-images.githubusercontent.com/40596171/42943184-b8653252-8b6a-11e8-82e0-0d804b302a9e.png)

As you can see, first try was correct:
![vnc04](https://user-images.githubusercontent.com/40596171/42943208-c9863b3a-8b6a-11e8-82f4-62aca7437b3b.png)

But in the end, we solved this problem. See our the solution (for Window 8) below:

1) (make sure that you use [rippletest] user: rippletest / pass: oloken21)

2) Check on the server if any processes is running <ps ax|grep vnc> 

3) If you see the process(es) - kill them <kill №proc>:
![2018-07-19_1608](https://user-images.githubusercontent.com/40596171/42944346-12a3bb28-8b6e-11e8-9f64-a65e96f7570f.png)

4) Check if there is no process <ps ax|grep vnc>

5) Start a new session with a new user <vncserver>

6) Check what port is used <ps ax|grep vnc>
![putty](https://user-images.githubusercontent.com/40596171/42944815-57d77e2c-8b6f-11e8-9781-fef7c2efb6cd.png)

7) Download VNC Viewer (in our case worked VNC Viewer from RealVNC.com)

8) When you run VNC Viewer you will see the window, where you have to add Remote computer address. For example 138.68.171.243:5901
![2018-07-19_1559](https://user-images.githubusercontent.com/40596171/42944876-7ea46e52-8b6f-11e8-90a8-e80991937242.png)

9) When you see new window, click OK:
![2018-07-19_1515](https://user-images.githubusercontent.com/40596171/42945677-a51e5834-8b71-11e8-8881-e6a2c249e18a.png)

10) In the password field put <ubuntudesktop18>

11) If you can't connect check process number again. And try to connect again

12) After you connected, you'll see the remote desktop

13) To run the test on a virtual machine, you have to do next:

14) Go to Home folder:
![2018-07-19_1517](https://user-images.githubusercontent.com/40596171/42945263-97acb214-8b70-11e8-84a6-1fae2f0fb6aa.png)

15) Then go to PulseTile-Tests:
![2018-07-19_1517_001](https://user-images.githubusercontent.com/40596171/42945347-d7435efa-8b70-11e8-835b-9b205d914166.png)

16) Click (right mouse button for right-handed users, and left mouse button for left-handed users) and in the appeared menu choose Open Terminal Here:
![2018-07-19_1516_001](https://user-images.githubusercontent.com/40596171/42945498-3d457ecc-8b71-11e8-996f-ab1fe5984326.png)

17) In the newly opened console type <nightwatch --env=dev_react> and click Enter

18) And you can see how your tests run:
![2018-07-19_1451](https://user-images.githubusercontent.com/40596171/42945797-f52b2276-8b71-11e8-8a26-d919a8b3524c.png)

**Comment by PhilBarrett** [comment]
@kuvakina Is this still an issue?

**Comment by kuvakina** [comment]
@PhilBarrett no, I'd checked the remote machine and everything is ok: file:///C:/Users/User/Documents/PROJECTS/PulseTile/2018-10-04_1841.png

We can move it to Dome @tony-shannon ?
