### ISSUE TITLE
End2End testing. Issue with Showcase job

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/PulseTile-React-Core#192]
@tony-shannon 

As we tried to find out a pattern in End2End testing for Showcase, we see the same error and failure:

1) Error at the beginning of the test:
![sc1](https://user-images.githubusercontent.com/40596171/42955388-4b819d3a-8b86-11e8-9e23-1d8ec6aa5d7f.png)

2) And failure:
![sc2](https://user-images.githubusercontent.com/40596171/42955579-7ad79a1c-8b86-11e8-9a17-bd0729d85d16.png)

I think we should first understand the reason why React tests fail and then maybe this issue could be solved.

**Comment by tony-shannon** [comment]
Agree @kuvakina Lets focus on React tests first

**Comment by tony-shannon** [comment]
ok to close this, thanks
