### ISSUE TITLE
End2End testing. Issue with Angular job

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/PulseTile-React-Core#193]
@tony-shannon 

As we tried to figure out a pattern in End2End testing for React, we noticed some issues:

1) Until Monday, 16.07.2018, jobs on Angular failed. Mostly that were the same errors (for 45-49 builds): 
![ang48](https://user-images.githubusercontent.com/40596171/42952165-82332e1c-8b80-11e8-862d-c29674ca815c.png)
We reproduced those failures manually and it appeared that tests work correct and problems were with the response from the server.

The same failures were for React. 

2) Monday morning we had a failure, that we couldn't reproduce:
![ang50](https://user-images.githubusercontent.com/40596171/42952549-62411776-8b81-11e8-9022-cf67b0937aae.png)
And problem was that we didn't see why tests show an error here:
![ang](https://user-images.githubusercontent.com/40596171/42952619-8e08ab9e-8b81-11e8-8941-20845390cf5d.png)

3) After Tony reboot EtherCIS, tests on Angular were successful:
![2018-07-19_1801](https://user-images.githubusercontent.com/40596171/42952692-b8562c6e-8b81-11e8-9c4e-782390f91798.png)

So I assume, that maybe failures with Angular jobs somehow were related to EtherCIS

**Comment by kuvakina** [comment]
@tony-shannon

Right now this problem with Angular E2E testing fails is fixed.

Approximately the problem was with EtherCIS: we think that EtherCIS servers were unavailable from time to time. But right now the jobs run successfully: https://www.screencast.com/t/2y7y9ggbg

Can we consider this issue Done?

**Comment by tony-shannon** [comment]
ok to close this thanks
