### ISSUE TITLE
End2End testing. Issue with React job

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/PulseTile-React-Core#194]
@tony-shannon 

As we tried to see a pattern in End2End testing for React, we noticed some issues:

1) Until Monday, 16.07.2018, jobs on React were failures. The fails were the same as for Angular before Monday https://github.com/PulseTile/PulseTile-React-Core/issues/193
And also the manual test showed that tests work correctly and the problem with the response from server:
  - Allergies failure:
This is the failure in the report:
![allergies_error_log](https://user-images.githubusercontent.com/40596171/42953638-9221814a-8b83-11e8-8ad5-c3c3ed6ef4ba.png)
We try to add allergy:
![pic1 allergies](https://user-images.githubusercontent.com/40596171/42953654-962047ea-8b83-11e8-90ac-2d0aee401761.png)
Response from the server that changes were saved: 
![pic2 allergies](https://user-images.githubusercontent.com/40596171/42953664-98a999c6-8b83-11e8-8ba0-f8ca25504a76.png)
And we don't see changes:
![pic3 allergies](https://user-images.githubusercontent.com/40596171/42953667-9b257d50-8b83-11e8-801a-957c065d203b.png)

The same was for PersonalNotes, Contacts, and Vaccination. 

There were more or fewer failures, it was different from test to test.

2) After Tony reboot EtherCIS, we were left with two failures, that we couldn't reproduce:
 - patientAccordionTest:
This is the failure in the report:
![expandbutton](https://user-images.githubusercontent.com/40596171/42954163-bb159f7c-8b84-11e8-98d8-15a3dbc83cc8.png)
This is what we see:
![expandbuttonweb](https://user-images.githubusercontent.com/40596171/42954186-c96ffdc4-8b84-11e8-8674-2771a5c48d90.png)

  -patientInformationTest:
This is the failure in the report:
![preferences](https://user-images.githubusercontent.com/40596171/42954212-da07cf72-8b84-11e8-9615-a3403ed47952.png)
And what we see:
![preferencesweb](https://user-images.githubusercontent.com/40596171/42954231-e42a0308-8b84-11e8-85de-f5d416c84483.png)

3) As we tried to run tests on the Remote desktop today, we got the same failure with patientAccordionTest:
![2018-07-19_1452](https://user-images.githubusercontent.com/40596171/42954357-298fa89e-8b85-11e8-80a1-a08ff7268d77.png)

But we couldn't continue the test after this, because we were thrown out from Remote desktop shortly after the next test started:
![2018-07-19_1510](https://user-images.githubusercontent.com/40596171/42954439-60104536-8b85-11e8-976a-5edde093d3f8.png)
![2018-07-19_1510_001](https://user-images.githubusercontent.com/40596171/42954446-6575a76e-8b85-11e8-96e1-f6a3c1ff39ce.png)

4) And the most confusing part is that local tests run mostly just fine. So we can't say, that the problem either with tests or code.

We'd like to ask maybe @robtweed help.

**Comment by kuvakina** [comment]
@tony-shannon 

Last week tests for React failed.
 
The problem was with a single test:
![2018-08-06_1510](https://user-images.githubusercontent.com/40596171/44042122-26da3928-9f28-11e8-861f-47e84e5a543c.png)

We think it was because at some point test was running out of memory. 

At the moment tests run successfully and don't fail: https://www.screencast.com/t/RXPzZmmp

But we'll monitor them for now.

**Comment by tony-shannon** [comment]
thanks
How can we monitor the memory?
Tony

**Comment by kuvakina** [comment]
We can monitor the memory using htop Command Under SSH Terminal. 

Once your server is connected with SSH, you can run Htop command by just typing htop and press Enter. 
A screen will open up as a result of this command where you can see where jobs run and what memory they use:
![memo02](https://user-images.githubusercontent.com/40596171/44083448-af1db0f0-9fbc-11e8-96cc-b255e61038d1.png)

As I said earlier, tests run just fine, but I'll continue monitoring them.

**Comment by kuvakina** [comment]
@tony-shannon 

Right now React tests are working correctly. Could we move this issue to Done?

**Comment by kuvakina** [comment]
Since last week (last week of September), for some reason React test started to fail. 

The problem occurred with those tests: patientAccordionTest & atientInformationTest

**Comment by PhilBarrett** [comment]
No further issues since this was resolved, closing issue
