### ISSUE TITLE
Set up Travis CI

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/PulseTile-React-Core#200]
Set up Travis CI for automatic Unit-testing for the following repos:

PulseTile-Core
PulseTile-Plus
LeadsCC

At the moment we set up Travis for PulseTile-React. To set up Travis for the rest repos we need login and password for PulseTile and LeadsCC

**Comment by tony-shannon** [comment]
ok I have set up trigger for both
PulseTile-Core
PulseTile-Plus

I dont have immediate access to LeedsCC , i can get it
Instead I want us to focus on Helm PHR theme as plugin, if we switch to that approach, we will hold that PHR theme in our repos for now, to make admin easier

**Comment by PhilBarrett** [comment]
Can this be closed now

**Comment by tony-shannon** [comment]
not yet, we need to revisit Travis CI setup @philbarrett

**Comment by tony-shannon** [comment]
closing as we are exploring Jenkins CI
