### ISSUE TITLE
Project Management issues to discuss - July/August 2018

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/PulseTile-React-Core#202]
we may not need an issue like this but it may help with project management over intervals
@kuvakina  let me know what you think, may save you from needing Google Docs to keep track?

**Comment by kuvakina** [comment]
@tony-shannon I think it's a great idea, thanks. I'm sure it will be faster and convenient for us.

**Comment by tony-shannon** [comment]
ok sure @kuvakina , just need to make sure these issues are timeboxed and dont get over long.. a month/two/three at a time may be reasonable, we can see how it works out
