### ISSUE TITLE
Help chat plugin

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/PulseTile-React-Core#205]
Task:                     To create a chat facility and add it to Helm-PHR-Theme plugin.

Related issue:       https://github.com/LeedsCC/Helm_PHR/issues/3  -  Add chat facility to Helm for trial

Use as reference:  https://www.click4assistance.co.uk/
[ToolScript.txt](https://github.com/PulseTile/PulseTile-React-Core/files/2314285/ToolScript.txt)

**Comment by tony-shannon** [comment]
not top priority, tackle this in context of Helm reBranding Sprint please

**Comment by kuvakina** [comment]
@tony-shannon got it, thank you

**Comment by PhilBarrett** [comment]
Duplicate of https://github.com/LeedsCC/Helm_PHR/issues/3
