### ISSUE TITLE
Automatic creation of the build

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/PulseTile-React-Core#206]
Make it the way that the build could be created automatically from different repos: -Core + -Silver + Helm-Theme

#201 Helm PHR Theme as plugin

**Comment by BogdanScherban** [comment]
@tony-shannon 

This task consists of following subtasks:

1) Container for non-core plugins was added into the Core-version:
https://github.com/PulseTile/PulseTile-React-Core/tree/develop

2) Plugins Vaccinations and TopThreeThings were updating for using via Container:
https://github.com/PulseTile-Plugins/Silver-Plugin-Vaccinations
https://github.com/PulseTile-Plugins/Silver-Plugin-TopThreeThings

3) All styles and images required for HelmPHR-theme were located in new plugin:
https://github.com/PulseTile-Plugins/Plugin-Helm-PHR-Theme 

4) Generator for automatic build creation:
https://github.com/RippleOSI/Helm-PHR-Generator

All these subtasks were done and merged.

**Comment by tony-shannon** [comment]
nice work, thank you

**Comment by kuvakina** [comment]
@tony-shannon Could we move it to Done?

**Comment by tony-shannon** [comment]
Please do
thanks T

**Comment by BogdanScherban** [comment]
@tony-shannon 

I've solved the issue with Feeds-plugin automatically adding by the way:
- Core was updated for this possibility;
- Feeds-plugin was updated and saved as separate repository;
- Add sub-generator for Feeds-plugin to the Generator for Helm-PHR.

PRs for first two issues:
https://github.com/PulseTile/PulseTile-React-Core/pull/211
https://github.com/PulseTile-Plugins/Silver-Feeds-Plugin/pull/1

When they will be approved, I'll check work of Generator and create PR for it.

**Comment by tony-shannon** [comment]
re:
"
@tony-shannon

I've solved the issue with Feeds-plugin automatically adding by the way:

Core was updated for this possibility;
Feeds-plugin was updated and saved as separate repository;
Add sub-generator for Feeds-plugin to the Generator for Helm-PHR.
PRs for first two issues:
#211
PulseTile-Plugins/Silver-Feeds-Plugin#1

When they will be approved, I'll check work of Generator and create PR for
it.
"

I cant see this on the thread? Have you moved or deleted it?
