### ISSUE TITLE
Feeds as Plugin please

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/PulseTile-React-Core#212]
@BogdanScherban  please update this issue

**Comment by BogdanScherban** [comment]
I've solved the issue with Feeds-plugin automatically adding by the way:

1) Core was updated for this possibility;
2) Feeds-plugin was updated and saved as separate repository;
3) Add sub-generator for Feeds-plugin to the Generator for Helm-PHR.

PRs for all three issues were approved.
New build (automatic generated) were upload to dev.ripple.foundation:8000

**Comment by tony-shannon** [comment]
thanks Bogdan

**Comment by tony-shannon** [comment]
see related Feeds plugin here
https://github.com/PulseTile-Plugins/Silver-Feeds-Plugin

**Comment by kuvakina** [comment]
@tony-shannon 

Could we move this issue to Done?
