### ISSUE TITLE
Appearance of 2 T&C for both desktop & mobile

### ISSUE THREAD

**Issue by kuvakina** [PulseTile/PulseTile-React-Core#258]
Right now, if I clear cookies and log in again to the site I see T&C twice: 

1) on login page after I clicked the Login button

2) when I already logged in 

See the video: I've tested login.myhelm.org and see this issue: https://www.screencast.com/t/b0J10Ss5

**Comment by PhilBarrett** [comment]
Plus padding and text wrapping isn't working as intended for the correct T&C page (1st time you see it) 

![Screen Shot 2018-10-16 at 09.42.25.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f56b7191a378e60c2f53415d4bbe5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5c3caa984ecb51f043e34d53ac113f6bf43b.png)
![Screen Shot 2018-10-16 at 09.44.25.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f56b7191a378e60c2f55415d4bbe5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecb51f043e34d53ac113e60f43b.png)

**Comment by PhilBarrett** [comment]
PB to test with new user and when the new build has been uploaded.

**Comment by kuvakina** [comment]
We still have 2 T&C : https://www.screencast.com/t/J4iUMmZzcoXB

**Comment by BogdanScherban** [comment]
@tony-shannon 
Suggest to remove T&C sub-generator from Helm Generator.
If we remove it T&C wouldn't occur when user already logged in.

**Comment by tony-shannon** [comment]
Agreed Bogdan, lets do that, please make sure you comment in the PR who you would reapply the T&C sub generator if we ever wanted to reverse that and use it again

**Comment by BogdanScherban** [comment]
Sub-generator for T&C was removed from Helm-generator.

README-file was updated.

Similar generator is used in Showcase-generator. If we want to return T&C to the Showcase, it is enough only to copy Sub-generator for T&C from Showcase-generator.

**Comment by BogdanScherban** [comment]
The issue has been done

**Comment by PhilBarrett** [comment]
Reviewed and working fine now, thanks
