### ISSUE TITLE
Showcase. Mobile experience. Search button

### ISSUE THREAD

**Issue by Alena1508** [PulseTile/PulseTile-React-Core#263]
When user click on search button he'll see notification window on mobile device. Although on mobile we already has search field and search icon. 
http://prntscr.com/l74pct

**Comment by kuvakina** [comment]
Related to issue [https://github.com/RippleOSI/Showcase-Project/issues/6](url)

**Comment by PhilBarrett** [comment]
Duplication of  https://github.com/RippleOSI/Showcase-Project/issues/6
