### ISSUE TITLE
Showcase. Mobile experience. Patient info goes missing

### ISSUE THREAD

**Issue by Alena1508** [PulseTile/PulseTile-React-Core#264]
When can see arrow button instead patient information on mobile device, but when we click on this arrow nothing happens. 
http://prntscr.com/l74uhv

**Comment by tony-shannon** [comment]
this also applies to the Helm view in mobile so is a priority
Patient Banner goes missing

![HelmMobileIssue.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bae28b4d734ec0013e1f936/125516c66e82c728ace21e0d46c091962eaf8cab86e5ba6ab74ee5916b0a65633b0ba92e7391a172fd1779000c0a4da9175f0d17adfcdd2ba6bf3f25835f5ebbd47f4366846c4ff8e7df46f554f832815d84b1b68b49c3e13522e3838c463919000ac4.PNG)

**Comment by Alena1508** [comment]
Hi @tony-shannon , 
I changed Helm for mobile according to mockups. Now we can see User name as in design (https://projects.invisionapp.com/d/main#/console/11007545/316291014/inspect). 
It looks this way:  http://prntscr.com/l8xn5m

An here I have a question. In green theme we have an arrow button by clicking on which we see the rest of patient info (http://prntscr.com/l8xuz4). But now this info is absent for Helm  mobile version as it's absent from design: 
So I wanted to ask if we should leave it like in mockups (w/o patient info) or we have to add patient info as it is in green theme?

**Comment by Alena1508** [comment]
Hi @tony-shannon ,
I changed Helm for mobile according to mockups. Now we can see the username as in design (https://projects.invisionapp.com/d/main#/console/11007545/316291014/inspect).
It looks this way: http://prntscr.com/l8xn5m

An here I have a question. Arrow button on green background (http://prntscr.com/l8xzfu). But now you’re absent for design:
I would like to see what you are looking for in mockups (w / o patient info)?

**Comment by kuvakina** [comment]
Related to issue #53 https://waffle.io/RippleOSI/combined-development-view/cards/5bc8a1e67b2479003c7c3686

**Comment by simongamester** [comment]
I've looked through @Alena1508 latest pull request https://github.com/PulseTile/PulseTile-React-Core/pull/269 and can see the drop down and patient name are coming through, however the Helm Theme is displaying the patient text and drop down icon in white text on a white background, so they are not viewable. The screen below shows the white text in place after being selected by dragging over it.
![Screenshot 2018-10-23 at 14.43.27.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb37967f01e4d00110fba95/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417773e7b57e32a64c5b27cf116284f5d585cb053181d1ba6acda6fb4bc2e75d80d58b8d2680973946e40a9ec821fb602ef29881ad3b3ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4fc85bf649e34b56a4133271ab.png)

**Comment by simongamester** [comment]
@Alena1508 @tony-shannon I've submitted a small PR to fix the text within the Helm theme for this issue:

https://github.com/PulseTile-Plugins/Plugin-Helm-PHR-Theme/pull/21

![Screenshot 2018-10-23 at 15.00.17.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb37967f01e4d00110fba95/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417773e7b57e32a64c5b27df1122b4f5e585cb053181d1ba6acda6fb4bc2e75d80d58b8d2680973946e40a9ec821fb602ef29881ad3b3ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4fc85bf648e34e53a2123471ab.png)

and

![Screenshot 2018-10-23 at 15.01.02.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb37967f01e4d00110fba95/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417773e7b57e32a64c5b27df1122a4f5f5d5cb053181d1ba6acda6fb4bc2e75d80d58b8d2680973946e40a9ec821fb602ef29881ad3b3ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4fc85bf648e34a51ac173271ab.png)
