### ISSUE TITLE
Multiple demographics API calls

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/PulseTile-React-Core#280]

**Comment by PhilBarrett** [comment]
Linked to https://github.com/LeedsCC/Helm-PHR-Project/issues/65

**Comment by PhilBarrett** [comment]
![image (1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46e1999b2487c3e1dea0fd0fe64de29b234324676b5ee17e7284e02dec177d560d0c1fa915585f4dffac8028f3e03962964e49bc8f3900299f7744eeaa880dbe06b0218e4b85bfb58a49c4ed3b27e099c2.png)

**Comment by BogdanScherban** [comment]
This issue is similar to https://github.com/LeedsCC/Helm-PHR-Project/issues/65

This issue has been done.

**Comment by PhilBarrett** [comment]
@BogdanScherban Has this change been made to React Core?

**Comment by kuvakina** [comment]
Checked.
We don't have multiple demographics API calls anymore.
See the video: https://www.screencast.com/t/9GycXLLB

@tony-shannon @PhilBarrett
