### ISSUE TITLE
PulseTile ReactJS - Unit Testing status

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/PulseTile-React-Core#40]
needs testing as per our test scripts to ensure matches Angular version functionality- for this block of work

**Comment by tony-shannon** [comment]
@anna-otrokhova can you please list the modules in React Block 1 
Can we check if the e2e tests cover these and have been run successfully?

**Comment by anna-otrokhova** [comment]
@tony-shannon
The Block 1 had the following headings:
Core application

Week 1: Graphs page (index) / Patient list page;
Week 2: Patient list extended functionality - counts, displayable columns switcher / User's profile page;
Week 3: Search functionality / Advanced search functionality / Application Preferences;
Week 4: Patient homepage (summary) / Sidebar Menu / Allergies heading;

P.S. (There wasn't included Search functionality / Advanced search functionality, Graphs page, Patient list page to End2End tests).

Block2 had the following headings:

Block 2: Headings
Week 5: Clinical notes heading / Contacts heading / Problems-Diagnosis heading;
Week 6: MDT heading / Medications heading / Orders heading;
Week 7: Personal Notes heading / Procedures heading / Referrals heading;
Week 8: Test results heading / Transfer of Care heading;

P.S. Clinical Notes, MDT heading, Orders heading, Procedures heading, Referrals heading, Test results heading, Transfer of Care heading weren't included to End2End tests.
Related issue:https://github.com/PulseTile/PulseTile-React/issues/79

**Comment by BogdanScherban** [comment]
Current test coverage 100% for LeedsCC theme probably was reached with settings MainTheme (instead of Leeds-theme).
It is necessary to make some changes in tests to provide required test coverage both for Main theme and Leeds theme.

**Comment by kuvakina** [comment]
@tony-shannon 
Unit tests were updated for work both with the Main theme and the LeedsCC. 

Can we consider this task as a Done?

**Comment by tony-shannon** [comment]
@kuvakina before we do.. can I get a view on this on the 2 key repos for PulseTile React please?
the Core repo + the Plus (inc Plugins) repo
are they both covered 100%?

**Comment by BogdanScherban** [comment]
![screenshot from 2018-07-10 14-11-32](https://user-images.githubusercontent.com/39263134/42506695-4ac38f30-844b-11e8-8370-8f1b0010c4ab.png)

@tony-shannon 
Hi, Tony! You can see the difference between LeedsCC-repo and Core-repo.
There are three plugins: Feeds, TopThreeThings and Vaccinations, which are presented in LeedsCC and absent in Core (as non-core plugins)
https://github.com/LeedsCC/PulseTile-React/tree/develop/src/components/pages
https://github.com/PulseTile/PulseTile-React-Core/tree/develop/src/components/pages

All none-core plugins were relocated to the separate repos in https://github.com/PulseTile-Plugins:
https://github.com/PulseTile-Plugins/PulseTile-React-Bronze-Plugins
https://github.com/PulseTile-Plugins/PulseTile-React-Carbon-Plugins
https://github.com/PulseTile-Plugins/PulseTile-React-Silver-Plugins

**Comment by BogdanScherban** [comment]
@tony-shannon 
Sorry, Tony! I thought you asked about plugins separation.

I've checked coverage now:
1) Test coverage at LeedsCC is 100%.
2) Unit tests at Core failed. I assume it could be because of last Oleg's changes (related to Counts) that wasn't covered by tests. We will wrote Oleg about this problem. He should update tests according to his changes.

**Comment by tony-shannon** [comment]
ok thanks for update @BogdanScherban

**Comment by tony-shannon** [comment]
I'm still not clear on % code coverage on this repo, can you clarify please

**Comment by tony-shannon** [comment]
@kuvakina says it is covered 100% by unit tests so I'm closing for now
