### ISSUE TITLE
change static information to the dynamic one from Patient Info drop-down

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile-React-Core#45]
Change static information to the dynamic one, it will be displayed in the Patient Info drop-down, potentially to the "application" endpoint. http://prntscr.com/gyzb6p
Here should be displayed the actual information about the version.

This issue is linked to this one: https://github.com/PulseTile/PulseTile/issues/47
https://github.com/RippleOSI/Ripple-Qewd/issues/59

**Comment by tony-shannon** [comment]
thanks @anna-otrokhova 

Again need to consider where this data should come from

Browser side PulseTile info can be provided by this codebase

Server side info (eg The QEWD-Ripple version) needs to come from a server side API
I don't see a related issue linked to anywhere..
Can you take a look please/consider raising a new issue here 
https://github.com/RippleOSI/Ripple-Qewd/issues

thanks
Tony

**Comment by anna-otrokhova** [comment]
@tony-shannon 
There is no update for a long time.

**Comment by robtweed** [comment]
The response from /api/initialise now includes a new property: version.  This is the version number taken from the package.json file for Ripple-QEWD

**Comment by robtweed** [comment]
Can this now be closed?  I believe QEWD is sending what's needed for this issue to be resolved
