### ISSUE TITLE
Empty string values are present in DB, the records which have such fields can't be edited

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile-React-Core#63]
There are some records, which were added as testing data I suppose manually. These records have empty fields by default and these fields are usually static (so when we create a new Allergy, for example, we don't enter these fields) Once we edit something we take the information which already has empty string values .
1) I suppose such records should be removed from DB. 
2) And test data should be checked for empty fields (string values) before adding to DB.

this is an example of such record http://prntscr.com/h7tnyj
http://prntscr.com/h7to26

@tony-shannon 
Could you help me, please? Whom should I mention here for checking?

This issue is related to this one https://github.com/RippleOSI/Ripple-Qewd/issues/62

**Comment by tony-shannon** [comment]
thanks @anna-otrokhova 

Please wait for a resolution on the Ripple  QEWD issue and retest when thats resolved
thanks
T

**Comment by anna-otrokhova** [comment]
@tony-shannon 
ok. Thank you. Once it is resolved I will test.

**Comment by tony-shannon** [comment]
Please see update on the related issue in QewdRipple 
https://github.com/RippleOSI/Ripple-Qewd/issues/62

**Comment by tony-shannon** [comment]
lets close this for now, as not a problem for some time
