### ISSUE TITLE
E2E testing 

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile-React-Core#79]
In process:
Setup nightwatch + webdriver + chrome driver
Add properties reading
Build Page Object hierarchy
Add Reporting
User login (Patient banner)
User Profile drop-down
Patient Information page
Patient Information (part of Accordion)
Patient Summary
Breadcrumbs
Patient Summary -> Redirection
Patient Summary -> Sidebar menu
Patient Headings > Problems/Diagnosis
Patient Headings > Medications
Patient Headings > Allergy
Patient Headings > Contacts
Patient Headings > Personal Notes
Patient Headings > Vaccinations
Update the instructions

**Comment by anna-otrokhova** [comment]
The Block 1 had the following headings:
Core application

Week 1: Graphs page (index) / Patient list page;
Week 2: Patient list extended functionality - counts, displayable columns switcher / User's profile page;
Week 3: Search functionality / Advanced search functionality / Application Preferences;
Week 4: Patient homepage (summary) / Sidebar Menu / Allergies heading;

P.S. (There wasn't included  Search functionality / Advanced search functionality, Graphs  page, Patient list page to End2End tests).

Block2 had the following headings:

Block 2: Headings
Week 5: Clinical notes heading / Contacts heading / Problems-Diagnosis heading;
Week 6: MDT heading / Medications heading / Orders heading;
Week 7: Personal Notes heading / Procedures heading / Referrals heading;
Week 8: Test results heading / Transfer of Care heading;

P.S. Clinical Notes, MDT heading,  Orders heading, Procedures heading, Referrals heading, Test results heading, Transfer of Care heading weren't included to End2End tests.

**Comment by tony-shannon** [comment]
Julia has access to the e2e server , IP ending x.x.x.243
confirmed access ok

**Comment by tony-shannon** [comment]
need to clear space ; issue #154

**Comment by BogdanScherban** [comment]
@tony-shannon 

Tony, I'm working on updating E2E testing for checking Showcase-, Dev_ang-, Rev_react- and Helm- versions. What have been done:
1) provided possibility to login with Auth0 or like at dev.ripple.foundation:8000, depends on version;
2) added settings which gives possibility to use different test data in different versions (for example user name and password etc.)

In all test-versions the following tests work correctly:
- allergiesTest;
- breadcrumbsTest;
- contactsTest;
- loginTest;
- medicationsTest;
- patientAccordionTest;
- patientInformationTest;
- sideBarMenuTest;
- vaccinationTest

These tests updates in process:
- patientSummaryRedirectionsTest;
- patientSummaryTest;
- problemsTest;
- profileTest;
- personalNotesTest.

I have some questions about these tests:

**ProfileTest**
1) Is it necessary to check version displaying (like "About Showcase Stack; PulseTile version 1.0.0/QEWD_Ripple version 15.6.2")? This data will be changed after each updating and our tests 
will be failed.

![screenshot from 2018-07-27 18-59-38](https://user-images.githubusercontent.com/39263134/43331833-3de12e12-91cf-11e8-9078-4bf0952c42a3.png)

2) User's email is absent in the Helm-version. Is it necessary to add email in Helm or don't check it in tests?

Helm:
![screenshot from 2018-07-27 19-00-16](https://user-images.githubusercontent.com/39263134/43331862-5184b1d2-91cf-11e8-9977-b482439ef694.png)

All others:
![screenshot from 2018-07-27 19-00-42](https://user-images.githubusercontent.com/39263134/43331894-621088e6-91cf-11e8-90b0-50e394d0bf98.png)

**patientSummaryRedirectionsTest** and **patientSummaryTest**
Some plugins have different names (like "Problems / Diagnosis" in Dev_react- and Dev_ang- and "Diagnosis" in Helm-). Should we rename it in repo or provide checking with different names?

**Comment by tony-shannon** [comment]
thanks @BogdanScherban 
Sorry for delay
In reply; wrt Helm End2End tests

1) can you check for any version number, not a particular defined number, if the number comes through ,thats a pass
2) lets leave email in the profile test for now
3) suggest repos should be renamed , and aligned between dev React & Helm at least
4) top 3 things needs to be added to the test

**Comment by BogdanScherban** [comment]
thanks, @tony-shannon 
It will be done

**Comment by kuvakina** [comment]
@tony-shannon 

As all new changes were implemented, could we consider this issue Done?

**Comment by PhilBarrett** [comment]
Closing, #194 remaining open in place
