### ISSUE TITLE
Leeds PHR Theming

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile-React-Core#81]
Tasks for LeedsPHR:

1) Restyling the site
2) Patient Summary
3) Footer
4) Header
5) Add new block "Vaccination" to Patient Summary
6) Change logic of displaying Patient Summary (Home) blocks:
- Full View
- Only Preview
- Only List
7) Push the changes to http://46.101.50.79/#/

**Comment by tony-shannon** [comment]
thanks Anna
Can you push LeedsPHR theming related changes to this repo for now please?
https://github.com/LeedsCC/PulseTile-React

We then need to work out which we keep in the main https://github.com/PulseTile/PulseTile-React repo

**Comment by anna-otrokhova** [comment]
@tony-shannon 

Sure, Tony. Alexey will push the code today or tomorrow.

**Comment by tony-shannon** [comment]
thanks Anna
T

**Comment by anna-otrokhova** [comment]
@tony-shannon 
Unfortunately, Alexey doesn't have permissions to push the code to that repo. Could you check it, please?  (Here is his account https://github.com/ahoncharov )

**Comment by tony-shannon** [comment]
Done , he has access

**Comment by tony-shannon** [comment]
@anna-otrokhova 
Can I get an update on the LeedsPHR code & where it sits.. some in this repo and some in the LeedsCC repo?

**Comment by anna-otrokhova** [comment]
All of the new functionality pieces have been committed to the main repo. We extended existing components to make them more flexible and added new headings for the pages that were introduced. Configuration file (themes.configs.js) determines the difference between Main React and LeedsPHR versions. This way maintenance and fine tuning of these two instances is exceedingly simplified as when any new feature or fix is committed to Main React repository it can easily become available for LeedsPHR instance.

We merged PulseTile-React version develop branch into LeedsPHR develop branch, so now they are equivalent. The difference lies only in LeedsPHR master branch, that contains its own configuration options that are specific for LeedsPHR theme. This way we can easily update the LeedsPHR version with latest Main React changes while configuration file of the LeedsPHR will always be on top of the new amends set.

**Comment by kbeloborodko** [comment]
@tony-shannon we merged the commit history inside the LeedsPHR fork. Now, if you go to "compare" section https://github.com/PulseTile/PulseTile-React/compare/master...LeedsCC:master, you can see that LeedsCC is only two commits ahead of the PulseTile-React repository. These commits contain changes to the readme and configuration files.

**Comment by tony-shannon** [comment]
I think this issue can be closed as we have changed course and moved towards core repo + plugins (inc themes) + generators
