### ISSUE TITLE
Add the heading Top Three Things (Project:Fork:LeedsPHR)

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile-React-Core#96]
Tasks to do:

- [x]  Replace the pictures in Patient Summary http://prntscr.com/hzij7o
- [x]  Add Top three things to Patient Summary
- [x] Add new heading "Top three things"
- [x] Add the banners to each heading
- [x] Move the changes to the Demo machine.
- [x] Change "Top Three Things" according to discussed topic.

We would need the pictures and endpoints to finish the task: 

- [x] endpoints
- [x] pictures

The potential url for Top three things could be: 
http://46.101.50.79/api/patients/9999999000/topThreeThings
we expect those fields http://prntscr.com/hzg0ru + userId

Related issue: https://github.com/RippleOSI/Ripple-Qewd/issues/71

**Comment by tony-shannon** [comment]
test update

**Comment by tony-shannon** [comment]
thanks Anna
V minor point , but that checklist above has elements from 2 issues:
1) Add Pictures to the PHR view
2) Add Heading: Top 3 things about me to PHR view
so as a rule I would split them out in future
thanks, T

**Comment by anna-otrokhova** [comment]
@tony-shannon 
Excuse me, Tony,  I am not sure whether I understand right what you mean here.

You want those tasks to be independent separate two issues?

**Comment by anna-otrokhova** [comment]
Rob, could you please copy the changes for "Top three things" to this machine http://46.101.50.79 ?
Also could you please implement PUT requests there (edit doesn't work)

**Comment by robtweed** [comment]
When you say that edit doesn't work, I'm not sure what you mean.  The PUT is implements and should behave exactly as a POST (it actually invokes the same code), in that it replaces the previous Top3Things with the updated information.  The URL is PUT /api/patients/:patientId/top3Things/:sourceId

The sourceId is actually ignored for this heading, as the PUT creates a new record with a new sourceId

If it's doing something unexpected, please provide more information on what you expected it to do and what it actually did that you thought was wrong.

Thanks
Rob

**Comment by robtweed** [comment]
Top3Things should now be on 46.101.50.79

**Comment by anna-otrokhova** [comment]
1) When I create using Postman I send this request:
{ "name1":"Item 1",
"description1":"My first problem", 
"name2":"Item 2", "description2":"My second problem", 
"name3":"Item 3", "3description3":"My third problem" }

and in Result, second and third items are the same (the third item isn't created) 

2)  http://prntscr.com/iau95o PUT request
http://prntscr.com/iauaas - Get after PUT (neither Issue #3 nor Description for it are updated, name is just duplicated from Issue #2 and description is empty)

@robtweed Please check it.

**Comment by robtweed** [comment]
3description3   is wrong in your request.  The property name should be:

description3

ie:
{ "name1":"Item 1",
"description1":"My first problem",
"name2":"Item 2", "description2":"My second problem",
"name3":"Item 3", "description3":"My third problem" }

The problem is that you are GETting the old sourceId instead of the latest.  No matter, I'll change the GET logic so you always get the latest, regardless of the sourceId you specify

**Comment by anna-otrokhova** [comment]
Thank you. It works now.

**Comment by tony-shannon** [comment]
It appears Creating (adding /POST) new issue was not finished on this module, so this issue needs to be reopened

**Comment by tony-shannon** [comment]
ok @juliashulga 
Understood

Just to note there are several patients we are trying to keep clean for demo purposes
esp NHS No 9999999015( Booth H)

@robtweed can you give Julia access to the PHR dev environment where she can access a range of patients for testing purposes.. (ie bypass the Citizen ID logon wayin)

thanks
T

**Comment by PhilBarrett** [comment]
Completed in React Admin
